### PR TITLE
Revert part of "Sync with mysql a bit to make the comparisson simple"

### LINKED ISSUE #226: Regression introduce with restarting slave pods with PVs
See https://github.com/sclorg/mysql-container/pull/215/files#r190365336

Should the example/replica template even have a PVC for the slave?
If so, how do we refactor the reference PR/commit to allow slave pod restart per the openshift/origin extended tests I referenced?

thanks

### PR DESCRIPTION
**Pull request by hhorak**
This reverts part of the commit ff1a1179c1f7914ad4a1c3a60d58f4cf7c07cd0c.
This should hopefully fix #226.

### CODE REVIEW

**Comment by hhorak** [comment]
[test-openshift]

**Comment by hhorak** [comment]
Since it is a revert, I believe no review is needed.

**Comment by bparees** [comment]
@hhorak what's your process for building/publishing the centos image these days?  (when should i expect to see an updated image w/ this change)

**Comment by hhorak** [comment]
@bparees it should be built after each commit. so it's a matter of minutes usually.

**Comment by bparees** [comment]
this has actually made things worse, the replicas aren't even coming up anymore:
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/20012/test_pull_request_origin_extended_image_ecosystem/896/

**Comment by bparees** [comment]
it looks like this test is failing because this check doesn't work anymore:

```
 mysqladmin -h localhost -uroot ping
mysqladmin: connect to server at 'localhost' failed
error: 'Your password has expired. To log in you must change it using a client that supports expired passwords.'
```

which is done by the test as part of prepping the replicas.  I need to look into whether that failure is expected.

**Comment by bparees** [comment]
poking around I *think* this is an issue of the test case having bit-rotted even more than we realized rather than this PR causing problems.  I'll dig further and report back.  (I still think this reversion was needed though)

**Comment by bparees** [comment]
ok i got the test passing again using the currently published mysql image.

Additional changes were required in the TC: https://github.com/openshift/origin/pull/20021

**Pull request merged**
