### PR TITLE
Deprecate MySQL 5.6

### PR DESCRIPTION
**Pull request by pkubatrh**

### CODE REVIEW

**Comment by omron93** [comment]
@pkubatrh Shouldn't `5.6` be also remove from templates in `./examples/`? (MYSQL_VERSION variable - `5.5` is still there too)
Or these templates are not used?

**Comment by pkubatrh** [comment]
Good point, thanks! Removed both versions from the description

**Comment by pkubatrh** [comment]
[test]

**Comment by pkubatrh** [comment]
[test]

**Comment by omron93** [comment]
Thanks.

**Pull request merged**
