### PR TITLE
add template icon

### PR DESCRIPTION
**Pull request by alfonsoalongi**
add template icon

### CODE REVIEW

**Comment by phracek** [comment]
[test][test-openshift][test-openshift-3]

**Comment by yselkowitz** [comment]
LGTM

**Comment by phracek** [comment]
@alfonsoalongi Can you please rebase this PR including `common` submodule? Then I will re-run tests and merge it. Thanks

**Comment by alfonsoalongi** [comment]
> @alfonsoalongi Can you please rebase this PR including `common` submodule? Then I will re-run tests and merge it. Thanks

Hello,
I rebased. I don't know if I followed the correct procedure.
These are the instructions I performed following the guide on https://gist.github.com/ravibhure/a7e0918ff4937c9ea1c456698dcd58aa

# Add the remote, call it "upstream":
# git remote add upstream https://github.com/whoever/whatever.git
git remote add upstream https://github.com/sclorg/mysql-container.git

# Fetch all the branches of that remote into remote-tracking branches, such as upstream/master:
git fetch upstream

# Make sure that you're on your master branch:
git checkout master

# Rewrite your master branch so that any commits of yours that aren't already in upstream/master are replayed on top of that other branch:
git rebase upstream/master

git pull
git status
git push origin master

**Comment by phracek** [comment]
[test-all]

**Comment by phracek** [comment]
Re-running tests because of infrastructure problems

[test]

**Comment by phracek** [comment]
[test-all]

**Comment by phracek** [comment]
rebased

[test-all]

**Review by phracek — APPROVED** [review]
LGTM. Let's wait for tests

**Pull request merged**
