### PR TITLE
Support building testing rhel9

### PR DESCRIPTION
**Pull request by phracek**
This pull request enables building and testing mysql-container 8.0 on RHEL9 host.

README.md files are also updated.

### CODE REVIEW

**Comment by phracek** [comment]
[test-all]

**Comment by phracek** [comment]
Diff between `8.0/Dockerfile.rhel8` and `8.0/Dockerfile.rhel9`

```bash
$ diff 8.0/Dockerfile.rhel8 8.0/Dockerfile.rhel9
1c1
< FROM ubi8/s2i-core
---
> FROM ubi9/s2i-core
30c30
<       name="rhel8/mysql-80" \
---
>       name="rhel9/mysql-80" \
33c33
<       usage="podman run -d -e MYSQL_USER=user -e MYSQL_PASSWORD=pass -e MYSQL_DATABASE=db -p 3306:3306 rhel8/mysql-80" \
---
>       usage="podman run -d -e MYSQL_USER=user -e MYSQL_PASSWORD=pass -e MYSQL_DATABASE=db -p 3306:3306 rhel9/mysql-80" \
41,42c41
< RUN yum -y module enable mysql:$MYSQL_VERSION && \
<     INSTALL_PKGS="policycoreutils rsync tar gettext hostname bind-utils groff-base mysql-server" && \
---
> RUN INSTALL_PKGS="policycoreutils rsync tar gettext hostname bind-utils groff-base mysql-server" && \
```

**Comment by phracek** [comment]
[test-all]

**Comment by hhorak** [comment]
LGTM, thanks!

**Pull request merged**
