### PR TITLE
tests: make sure the testsuite ends with 1 if any test fail

### PR DESCRIPTION
**Pull request by zmiklank**

### CODE REVIEW

**Comment by zmiklank** [comment]
[test]

**Comment by zmiklank** [comment]
[test]

**Comment by zmiklank** [comment]
These failures seem relevant, I need to go through them.

**Comment by zmiklank** [comment]
[test]

**Comment by zmiklank** [comment]
[test-all]

**Comment by hhorak** [comment]
lgtm

**Review by hhorak — APPROVED** [review]
The changes make sense, CI is pretty green, I think we can merge it.

**Pull request merged**
