### PR TITLE
Clean yum cache for every available repository

### PR DESCRIPTION
**Pull request by pkubatrh**

### CODE REVIEW

**Comment by hhorak** [comment]
[test]

**Comment by hhorak** [comment]
[test]

**Comment by hhorak** [comment]
[test]

**Comment by hhorak** [comment]
[test]

**Comment by kubco2** [comment]
[test]

**Comment by kubco2** [comment]
@pkubatrh  rebase please, rhel8 should pass.

**Comment by pkubatrh** [comment]
Rebased

**Comment by pkubatrh** [comment]
Test failure seems like we need https://github.com/sclorg/mysql-container/pull/251 for Fedora as well. Will do a follow up later

**Pull request merged**
