### PR TITLE
Use generic run tests function

### PR DESCRIPTION
**Pull request by zmiklank**

### CODE REVIEW

**Comment by phracek** [comment]
[test-all]

**Review by phracek — CHANGES_REQUESTED** [review]
Everything LGTM. I would like to analyze logs in deep. Can you please rebase this pull request? I would like to check if testing farm and tests are working properly.

**Comment by zmiklank** [comment]
[test-all]

**Comment by phracek** [comment]
There is a problem with RHELí unsubscribed host:

```bash

Red Hat Universal Base Image 9 (RPMs) - BaseOS  453 kB/s | 543 kB     00:01    
Red Hat Universal Base Image 9 (RPMs) - AppStre 1.2 MB/s | 1.4 MB     00:01    
Red Hat Universal Base Image 9 (RPMs) - CodeRea  21 kB/s |  14 kB     00:00    
Package rsync-3.2.3-9.el9_0.1.x86_64 is already installed.
Package tar-2:1.34-3.el9.x86_64 is already installed.
Package gettext-0.21-7.el9.x86_64 is already installed.
Package groff-base-1.22.4-10.el9.x86_64 is already installed.
No match for argument: mysql-server
Error: Unable to find a match: mysql-server
```

@hhorak @pkubatrh How to drive this problem? File an issue? Where?

**Review by phracek — APPROVED** [review]
LGTM.

**Pull request merged**
