### PR TITLE
Support for testing image in CentOS Stream 9

### PR DESCRIPTION
**Pull request by phracek**
This pull request adds support for testing mysql-container in CentOS Stream 9.

Dockerfile change is:

```
$ diff 8.0/Dockerfile.rhel8 8.0/Dockerfile.c9s
1c1
< FROM ubi8/s2i-core
---
> FROM quay.io/sclorg/s2i-core-c9s:c9s
30c30
<       name="rhel8/mysql-80" \
---
>       name="sclorg/mysql-80-c9s" \
33c33
<       usage="podman run -d -e MYSQL_USER=user -e MYSQL_PASSWORD=pass -e MYSQL_DATABASE=db -p 3306:3306 rhel8/mysql-80" \
---
>       usage="podman run -d -e MYSQL_USER=user -e MYSQL_PASSWORD=pass -e MYSQL_DATABASE=db -p 3306:3306 quay.io/sclorg/mysql-80-c9s:c9s" \
41,42c41
< RUN yum -y module enable mysql:$MYSQL_VERSION && \
<     INSTALL_PKGS="policycoreutils rsync tar gettext hostname bind-utils groff-base mysql-server" && \
---
> RUN INSTALL_PKGS="policycoreutils rsync tar gettext hostname bind-utils groff-base mysql-server" && \
```
Signed-off-by: Petr "Stone" Hracek <phracek@redhat.com>

### CODE REVIEW

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
Not relevant for C9S.

[test-openshift]

**Comment by phracek** [comment]
[test-all]

**Comment by zmiklank** [comment]
The test failures seem to be similar as in https://github.com/sclorg/mariadb-container/pull/161.

**Comment by phracek** [comment]
[test-all]

**Review by zmiklank — APPROVED** [review]

**Pull request merged**
