### PR TITLE
Build mysql 8.0 by default and fix installation in CentOS

### PR DESCRIPTION
**Pull request by omron93**
SSIA

Fixes: #243

### CODE REVIEW

**Comment by omron93** [comment]
[test-openshift]

**Comment by omron93** [comment]
@hhorak @kubco2 @mschorm Please take a look in fedora build log. `semanage` [1] in F29 is failing the build. Mentioned bug is fixed, so could it be possible to remove `semanage`? (but I don't know the full story behind this)

Fedora bug for `semanage` problem in container build - [2]

[1] https://src.fedoraproject.org/rpms/community-mysql/blob/f29/f/community-mysql.spec#_715
[2] https://bugzilla.redhat.com/show_bug.cgi?id=1558861

**Comment by hhorak** [comment]
[test]

**Comment by hhorak** [comment]
[test-openshift]

**Comment by phracek** [comment]
It seems like there is not installed `git` command in rhel8 system.

```bash
bash: git: command not found
Build step 'Execute shell' marked build as failure
[PostBuildScript] - Execution post build scripts.
[rhscl-images-mysql-rh-rhel8@2] $ /bin/bash /tmp/jenkins8915332865140162122.sh
Warning: Permanently added '10.0.150.243' (ECDSA) to the list of known hosts.
bash: line 2: git: command not found
```

**Comment by hhorak** [comment]
I believe these changes are no longer required, the rh-mysql80 is already in the properly released version and it is also present in the Makefile. Thus, closing this PR.

**Pull request closed without merging**
