### PR TITLE
tests: add run-openshift

### PR DESCRIPTION
**Pull request by pkubatrh**
+ fix templates pointing to a symlink

### CODE REVIEW

**Comment by pkubatrh** [comment]
[test-openshift]

**Comment by pkubatrh** [comment]
@omron93 Are the centos openshift tests enabled for this repository?

**Comment by pkubatrh** [comment]
@hhorak @pvalena ptal

Changes are the same as for mariadb

**Comment by pvalena** [comment]
@pkubatrh, can you please put template updates and run-openshift changes separately (into another PR)? So we can confirm tests work with the older version of templates at first.

**Comment by pkubatrh** [comment]
I dont think it makes any sense for this PR, since the only changes in templates are pointers to readme. But will do for mariadb.

**Comment by pvalena** [comment]
Yes, that's correct. I've missed that. Thanks!

**Comment by omron93** [comment]
Tests are passing. Also this is almost same as OpenShift tests for mariadb-container. Merging.

@pkubatrh Thanks.

**Pull request merged**
