### PR TITLE
tests: use the tfaga wrapper in the testing actions

### PR DESCRIPTION
**Pull request by zmiklank**
See [TFaGA Wrapper](https://github.com/sclorg/tfaga-wrapper/) and https://github.com/sclorg/tfaga-wrapper/issues/8.

### CODE REVIEW

**Comment by phracek** [comment]
It looks like mysql-container is failing even in case all tests are passing.
Similar to this PR https://github.com/sclorg/mariadb-container/pull/193

[test]

**Comment by zmiklank** [comment]
> It looks like mysql-container is failing even in case all tests are passing. Similar to this PR [sclorg/mariadb-container#193](https://github.com/sclorg/mariadb-container/pull/193)
> 
> [test]

Changes in this PR will not be seen in the tests you have just triggered here. What do you want to test?
The PR you linked is about something different than tfaga wrapper. Can you please show where the tests are misbehaving?

**Comment by zmiklank** [comment]
[test]

**Comment by zmiklank** [comment]
There seem to be some problem in the TMT plan in RHEL9 - 8.0 use case. Can we merge this? @phracek

**Review by phracek — APPROVED** [review]
LGTM

**Pull request merged**
