### PR TITLE
Do not use VOLUME command in Dockerfiles

### PR DESCRIPTION
**Pull request by pkubatrh**
As it does not work in Openshift Online for builder images for now.

### CODE REVIEW

**Comment by pkubatrh** [comment]
[test-openshift]

**Comment by pkubatrh** [comment]
[test][test-openshift]

**Comment by mfojtik** [comment]
@pkubatrh @hhorak this is breaking the new-app flow where we detected the VOLUME and notified users to create PVC for that volume so they data will be persisted.

**Comment by hhorak** [comment]
Ok, will revert the change.

**Comment by pkubatrh** [comment]
Since we triggered some failure on origin side of things, I now wonder if it was ok for us to remove the VOLUME definitions in other images...

**Comment by hhorak** [comment]
@mfojtik thinks it is, because there is still the bz#1481918.. so we should probably have volume for databases, but not elsewhere.

**Pull request merged**
