### PR TITLE
add imagestreams to image repo

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@praiskup @hhorak @pkubatrh @pvalena ptal

**Comment by pkubatrh** [comment]
Templates are already present in `examples/`

**Comment by bparees** [comment]
@pkubatrh sorry, that was a mistake.  PR updated.

**Comment by bparees** [comment]
@pkubatrh i'm going to self merge this since it's only additive and i need to move forward on some dependent work, but if you have other concerns(I removed the templates) feel free to revert it.

**Pull request merged**
